ALTER TABLE foodhelp.foods DROP CONSTRAINT IF EXISTS foods_base_quantity_check;
ALTER TABLE foodhelp.foods ALTER COLUMN base_quantity TYPE text USING base_quantity::text;
ALTER TABLE foodhelp.foods ALTER COLUMN base_quantity DROP NOT NULL;
ALTER TABLE foodhelp.foods ALTER COLUMN unit DROP NOT NULL;
ALTER TABLE foodhelp.foods ADD COLUMN is_free_consumption boolean NOT NULL DEFAULT false;

ALTER TABLE foodhelp.foods DROP CONSTRAINT IF EXISTS foods_food_group_check;
ALTER TABLE foodhelp.foods ADD CONSTRAINT foods_food_group_check
  CHECK (food_group IN ('Frutas', 'Verduras', 'Cereales y leguminosas', 'Proteinas', 'Grasas', 'Azucar', 'Condimentos', 'Bebidas', 'Antojos'));
ALTER TABLE foodhelp.foods ADD CONSTRAINT foods_portion_validity_check CHECK (
  (is_free_consumption AND base_quantity IS NULL AND unit IS NULL)
  OR
  (NOT is_free_consumption AND base_quantity IS NOT NULL
    AND base_quantity ~ '^([1-9][0-9]*([.][0-9]+)?|0?[.][0-9]*[1-9][0-9]*|[1-9][0-9]*/[1-9][0-9]*)$'
    AND unit IS NOT NULL AND btrim(unit) <> '')
);

ALTER TABLE foodhelp.prescription_items DROP CONSTRAINT IF EXISTS prescription_items_food_group_check;
ALTER TABLE foodhelp.prescription_items ADD CONSTRAINT prescription_items_food_group_check
  CHECK (food_group IN ('Frutas', 'Verduras', 'Cereales y leguminosas', 'Proteinas', 'Grasas', 'Azucar'));

WITH catalog(name, food_group, base_quantity, unit, is_free_consumption) AS (VALUES
  ('Agua de coco', 'Frutas', '325', 'ml', false),
  ('Caña', 'Frutas', '250', 'g', false),
  ('Capulín', 'Frutas', '3', 'tazas', false),
  ('Cerezas frescas', 'Frutas', '20', 'piezas', false),
  ('Chabacano', 'Frutas', '4', 'piezas', false),
  ('Chicozapote', 'Frutas', '1/2', 'piezas', false),
  ('Chirimoya', 'Frutas', '1/3', 'piezas', false),
  ('Ciruela', 'Frutas', '3', 'piezas', false),
  ('Coctel de frutas', 'Frutas', '1', 'tazas', false),
  ('Dátil fresco', 'Frutas', '2', 'piezas', false),
  ('Durazno', 'Frutas', '2', 'piezas', false),
  ('Frambuesa', 'Frutas', '3/4', 'tazas', false),
  ('Fresa', 'Frutas', '1', 'tazas', false),
  ('Granada china', 'Frutas', '2', 'piezas', false),
  ('Granada roja', 'Frutas', '1', 'piezas', false),
  ('Guanábana', 'Frutas', '1', 'piezas', false),
  ('Guayaba', 'Frutas', '3', 'piezas', false),
  ('Higo', 'Frutas', '2', 'piezas', false),
  ('Kiwi', 'Frutas', '2', 'piezas', false),
  ('Lichis', 'Frutas', '12', 'piezas', false),
  ('Lima', 'Frutas', '3', 'piezas', false),
  ('Mamey', 'Frutas', '1/3', 'piezas', false),
  ('Mandarina', 'Frutas', '2', 'piezas', false),
  ('Mango grande', 'Frutas', '1/2', 'piezas', false),
  ('Mango manila', 'Frutas', '1', 'piezas', false),
  ('Manzana', 'Frutas', '1', 'piezas', false),
  ('Melón', 'Frutas', '1', 'tazas', false),
  ('Mora azul', 'Frutas', '3/4', 'tazas', false),
  ('Naranja', 'Frutas', '2', 'piezas', false),
  ('Papaya', 'Frutas', '1', 'tazas', false),
  ('Pera', 'Frutas', '1', 'piezas', false),
  ('Piña', 'Frutas', '1', 'rebanada', false),
  ('Pitahaya', 'Frutas', '2', 'piezas', false),
  ('Plátano dominico', 'Frutas', '2', 'piezas', false),
  ('Plátano tabasco', 'Frutas', '1/2', 'piezas', false),
  ('Sandía', 'Frutas', '1', 'tazas', false),
  ('Tamarindo pelado', 'Frutas', '1/4', 'tazas', false),
  ('Tejocote', 'Frutas', '2', 'piezas', false),
  ('Toronja', 'Frutas', '1/2', 'piezas', false),
  ('Tuna', 'Frutas', '2', 'piezas', false),
  ('Uva', 'Frutas', '1', 'tazas', false),
  ('Zapote negro', 'Frutas', '1/2', 'piezas', false),
  ('Zarzamora', 'Frutas', '3/4', 'tazas', false),

  ('Amaranto', 'Cereales y leguminosas', '1/4', 'tazas', false),
  ('Arroz blanco', 'Cereales y leguminosas', '1/4', 'tazas', false),
  ('Arroz integral o salvaje', 'Cereales y leguminosas', '1/3', 'tazas', false),
  ('Avena cocida', 'Cereales y leguminosas', '3/4', 'tazas', false),
  ('Avena cruda', 'Cereales y leguminosas', '1/4', 'tazas', false),
  ('Barrita de cereal', 'Cereales y leguminosas', '1', 'piezas', false),
  ('Baguette', 'Cereales y leguminosas', '1/7', 'piezas', false),
  ('Bolillo con migajón', 'Cereales y leguminosas', '1/3', 'piezas', false),
  ('Bolillo sin migajón', 'Cereales y leguminosas', '1/2', 'piezas', false),
  ('Camote cocido', 'Cereales y leguminosas', '1/4', 'tazas', false),
  ('Cereal sin azúcar', 'Cereales y leguminosas', '1/2', 'tazas', false),
  ('Chícharos', 'Cereales y leguminosas', '1/2', 'tazas', false),
  ('Churritos de nopal', 'Cereales y leguminosas', '1/2', 'bolsa', false),
  ('Cous cous', 'Cereales y leguminosas', '1/3', 'tazas', false),
  ('Croutones', 'Cereales y leguminosas', '1/4', 'tazas', false),
  ('Elote desgranado', 'Cereales y leguminosas', '1/2', 'tazas', false),
  ('Elote entero', 'Cereales y leguminosas', '1/2', 'piezas', false),
  ('Fideos de arroz cocidos', 'Cereales y leguminosas', '1/4', 'tazas', false),
  ('Frijoles de la olla', 'Cereales y leguminosas', '1/2', 'tazas', false),
  ('Galletas habaneras', 'Cereales y leguminosas', '4', 'piezas', false),
  ('Galletas marías', 'Cereales y leguminosas', '5', 'piezas', false),
  ('Galletas de avena', 'Cereales y leguminosas', '1', 'piezas', false),
  ('Garbanzos cocidos', 'Cereales y leguminosas', '1/2', 'tazas', false),
  ('Granola sin azúcar', 'Cereales y leguminosas', '2', 'cucharadas', false),
  ('Habas cocidas', 'Cereales y leguminosas', '1/2', 'tazas', false),
  ('Harina de avena', 'Cereales y leguminosas', '1/4', 'tazas', false),
  ('Leche de arroz', 'Cereales y leguminosas', '1', 'tazas', false),
  ('Leche de avena', 'Cereales y leguminosas', '1', 'tazas', false),
  ('Lentejas cocidas', 'Cereales y leguminosas', '1/2', 'tazas', false),
  ('Palomitas naturales', 'Cereales y leguminosas', '3', 'tazas', false),
  ('Pan de caja chico', 'Cereales y leguminosas', '1', 'rebanada', false),
  ('Pan de caja grande', 'Cereales y leguminosas', '3/4', 'rebanada', false),
  ('Pan pita integral', 'Cereales y leguminosas', '1/2', 'piezas', false),
  ('Pan de hamburguesa', 'Cereales y leguminosas', '1/3', 'piezas', false),
  ('Pan de hot dog', 'Cereales y leguminosas', '1/2', 'piezas', false),
  ('Pan thins integral', 'Cereales y leguminosas', '2', 'piezas', false),
  ('Papa mediana', 'Cereales y leguminosas', '1', 'piezas', false),
  ('Pasta cocida', 'Cereales y leguminosas', '1/2', 'tazas', false),
  ('Pasta sin cocer', 'Cereales y leguminosas', '20', 'g', false),
  ('Quinoa cocida', 'Cereales y leguminosas', '1/3', 'tazas', false),
  ('Quinoa inflada', 'Cereales y leguminosas', '1', 'tazas', false),
  ('Salmas', 'Cereales y leguminosas', '1', 'paquete', false),
  ('Tortillas de harina blanca', 'Cereales y leguminosas', '1/2', 'piezas', false),
  ('Tortillas de harina integral', 'Cereales y leguminosas', '1', 'piezas', false),
  ('Tortillas de maíz', 'Cereales y leguminosas', '1', 'piezas', false),
  ('Tortillas de nopal', 'Cereales y leguminosas', '2', 'piezas', false),
  ('Tortitas de arroz inflado', 'Cereales y leguminosas', '2', 'piezas', false),
  ('Tortada horneada', 'Cereales y leguminosas', '1.5', 'piezas', false),
  ('Totopos de nopal', 'Cereales y leguminosas', '1', 'tazón', false),

  ('Arrachera', 'Proteinas', '30', 'g', false),
  ('Atún en lata', 'Proteinas', '1/3', 'lata', false),
  ('Atún en sobre', 'Proteinas', '1/2', 'sobre', false),
  ('Atún fresco', 'Proteinas', '40', 'g', false),
  ('Barbacoa (maciza)', 'Proteinas', '30', 'g', false),
  ('Bistec de res', 'Proteinas', '30', 'g', false),
  ('Camarón', 'Proteinas', '5', 'piezas', false),
  ('Carne molida sin grasa', 'Proteinas', '30', 'g', false),
  ('Carnitas (maciza)', 'Proteinas', '30', 'g', false),
  ('Cecina', 'Proteinas', '30', 'g', false),
  ('Claras de huevo', 'Proteinas', '2', 'piezas', false),
  ('Huevo entero', 'Proteinas', '1', 'piezas', false),
  ('Jamón de pavo', 'Proteinas', '2', 'rebanadas', false),
  ('Jamón de pierna', 'Proteinas', '1', 'rebanadas', false),
  ('Leche alta en proteína', 'Proteinas', '1/2', 'taza', false),
  ('Lomo de cerdo', 'Proteinas', '40', 'g', false),
  ('Machaca', 'Proteinas', '13', 'g', false),
  ('Mariscos', 'Proteinas', '40', 'g', false),
  ('Muslo de pollo', 'Proteinas', '1/2', 'piezas', false),
  ('Pavo', 'Proteinas', '45', 'g', false),
  ('Pechuga de pavo', 'Proteinas', '2', 'rebanadas', false),
  ('Pechuga de pollo', 'Proteinas', '30', 'g', false),
  ('Pescado blanco', 'Proteinas', '40', 'g', false),
  ('Pierna de pollo', 'Proteinas', '1', 'piezas', false),
  ('Pollo deshebrado', 'Proteinas', '30', 'g', false),
  ('Proteínas sin carbs', 'Proteinas', '1/3', 'cucharadas', false),
  ('Pulpo', 'Proteinas', '45', 'g', false),
  ('Queso cottage', 'Proteinas', '3', 'cucharadas', false),
  ('Queso de cabra', 'Proteinas', '30', 'g', false),
  ('Queso feta', 'Proteinas', '30', 'g', false),
  ('Queso manchego light', 'Proteinas', '30', 'g', false),
  ('Queso mozzarella', 'Proteinas', '40', 'g', false),
  ('Queso oaxaca light', 'Proteinas', '30', 'g', false),
  ('Queso panela light', 'Proteinas', '40', 'g', false),
  ('Queso parmesano', 'Proteinas', '3', 'cucharadas', false),
  ('Requesón', 'Proteinas', '2', 'cucharadas', false),
  ('Salchicha de pavo', 'Proteinas', '1', 'piezas', false),
  ('Salmón', 'Proteinas', '40', 'g', false),
  ('Surimi', 'Proteinas', '1', 'barra', false),
  ('Tempeh', 'Proteinas', '100', 'g', false),
  ('Tofu', 'Proteinas', '65', 'g', false),
  ('Trucha', 'Proteinas', '40', 'g', false),
  ('Yogurt griego', 'Proteinas', '1/2', 'taza', false),

  ('Aceite de aguacate', 'Grasas', '1', 'cucharaditas', false),
  ('Aceite de canola puro', 'Grasas', '1', 'cucharaditas', false),
  ('Aceite de coco', 'Grasas', '1', 'cucharaditas', false),
  ('Aceite de oliva', 'Grasas', '1', 'cucharaditas', false),
  ('Aceite de pepita de uva', 'Grasas', '1', 'cucharaditas', false),
  ('Aceitunas', 'Grasas', '5', 'piezas', false),
  ('Aderezo light', 'Grasas', '1', 'cucharadas', false),
  ('Aguacate', 'Grasas', '1/3', 'piezas', false),
  ('Cacao en polvo', 'Grasas', '1', 'cucharadas', false),
  ('Cacao nibs', 'Grasas', '2', 'cucharaditas', false),
  ('Chocolate amargo S/A', 'Grasas', '10', 'g', false),
  ('Coco rallado S/A', 'Grasas', '2', 'cucharadas', false),
  ('Ghee', 'Grasas', '1', 'cucharaditas', false),
  ('Guacamole', 'Grasas', '2', 'cucharadas', false),
  ('Leche de almendras', 'Grasas', '1', 'taza', false),
  ('Leche de coco S/A', 'Grasas', '1/2', 'taza', false),
  ('Linaza molida', 'Grasas', '2', 'cucharaditas', false),
  ('Mantequilla', 'Grasas', '1', 'cucharaditas', false),
  ('Mayonesa', 'Grasas', '1', 'cucharadas', false),
  ('Vinagreta', 'Grasas', '1', 'cucharadas', false),
  ('Ajonjolí', 'Grasas', '2', 'cucharadas', false),
  ('Almendras', 'Grasas', '5', 'piezas', false),
  ('Cacahuates naturales', 'Grasas', '7', 'piezas', false),
  ('Chía', 'Grasas', '4', 'cucharadas', false),
  ('Chilorio de soya', 'Grasas', '22', 'g', false),
  ('Crema de almendras', 'Grasas', '1', 'cucharadas', false),
  ('Crema de cacahuate', 'Grasas', '1', 'cucharadas', false),
  ('Hummus', 'Grasas', '2', 'cucharadas', false),
  ('Macadamias', 'Grasas', '2', 'piezas', false),
  ('Nueces', 'Grasas', '4', 'piezas', false),
  ('Nuez de la india', 'Grasas', '4', 'piezas', false),
  ('Pepitas', 'Grasas', '30', 'piezas', false),
  ('Piñón', 'Grasas', '2', 'cucharaditas', false),
  ('Pistaches', 'Grasas', '9', 'piezas', false),
  ('Semillas de calabaza', 'Grasas', '2', 'cucharadas', false),
  ('Semillas de hemp', 'Grasas', '2', 'cucharaditas', false),
  ('Semillas de girasol', 'Grasas', '2', 'cucharadas', false),
  ('Tahini', 'Grasas', '1', 'cucharadas', false),

  ('Agua de sabor', 'Azucar', '1', 'vaso', false),
  ('Agua quina', 'Azucar', '125', 'ml', false),
  ('Arándanos y pasas', 'Azucar', '1', 'puñito', false),
  ('Azúcar blanca o morena', 'Azucar', '1', 'cucharada', false),
  ('Bebida deportiva', 'Azucar', '125', 'ml', false),
  ('Cajeta', 'Azucar', '1', 'cucharada', false),
  ('Caramelos', 'Azucar', '2', 'piezas', false),
  ('Cátsup', 'Azucar', '1', 'cucharada', false),
  ('Gelatina', 'Azucar', '1/3', 'taza', false),
  ('Gomitas', 'Azucar', '3', 'piezas', false),
  ('Jugo natural o envasado', 'Azucar', '125', 'ml', false),
  ('Mermelada', 'Azucar', '1', 'cucharada', false),
  ('Miel de abeja', 'Azucar', '1', 'cucharada', false),
  ('Nieve de frutas', 'Azucar', '1/2', 'taza', false),
  ('Nutella', 'Azucar', '1', 'cucharada', false),
  ('Paleta de agua', 'Azucar', '1/2', 'piezas', false),
  ('Refresco', 'Azucar', '90', 'ml', false),

  ('Acelga', 'Verduras', NULL, NULL, true),
  ('Alcachofa', 'Verduras', NULL, NULL, true),
  ('Alga', 'Verduras', NULL, NULL, true),
  ('Arúgula', 'Verduras', NULL, NULL, true),
  ('Berenjena', 'Verduras', NULL, NULL, true),
  ('Berros', 'Verduras', NULL, NULL, true),
  ('Betabel', 'Verduras', NULL, NULL, true),
  ('Brócoli', 'Verduras', NULL, NULL, true),
  ('Calabacita', 'Verduras', NULL, NULL, true),
  ('Calabaza de castilla', 'Verduras', NULL, NULL, true),
  ('Cebolla', 'Verduras', NULL, NULL, true),
  ('Champiñón', 'Verduras', NULL, NULL, true),
  ('Chayote', 'Verduras', NULL, NULL, true),
  ('Chile (todo tipo)', 'Verduras', NULL, NULL, true),
  ('Cilantro', 'Verduras', NULL, NULL, true),
  ('Col', 'Verduras', NULL, NULL, true),
  ('Coles de Bruselas', 'Verduras', NULL, NULL, true),
  ('Coliflor', 'Verduras', NULL, NULL, true),
  ('Ejote', 'Verduras', NULL, NULL, true),
  ('Espárrago', 'Verduras', NULL, NULL, true),
  ('Espinaca', 'Verduras', NULL, NULL, true),
  ('Flor de calabaza', 'Verduras', NULL, NULL, true),
  ('Germinados', 'Verduras', NULL, NULL, true),
  ('Huitlacoche', 'Verduras', NULL, NULL, true),
  ('Jengibre', 'Verduras', NULL, NULL, true),
  ('Jícama', 'Verduras', NULL, NULL, true),
  ('Jitomate', 'Verduras', NULL, NULL, true),
  ('Kale', 'Verduras', NULL, NULL, true),
  ('Lechuga', 'Verduras', NULL, NULL, true),
  ('Nopal', 'Verduras', NULL, NULL, true),
  ('Palmitos', 'Verduras', NULL, NULL, true),
  ('Pepino', 'Verduras', NULL, NULL, true),
  ('Perejil', 'Verduras', NULL, NULL, true),
  ('Pimiento', 'Verduras', NULL, NULL, true),
  ('Puré de tomate', 'Verduras', NULL, NULL, true),
  ('Rábano', 'Verduras', NULL, NULL, true),
  ('Salsa verde o roja', 'Verduras', NULL, NULL, true),
  ('Tomate', 'Verduras', NULL, NULL, true),
  ('Verdolaga', 'Verduras', NULL, NULL, true),
  ('Zanahoria', 'Verduras', NULL, NULL, true),

  ('Ajo', 'Condimentos', NULL, NULL, true),
  ('Caldo de res o pollo S/G', 'Condimentos', NULL, NULL, true),
  ('Canela', 'Condimentos', NULL, NULL, true),
  ('Chamoy S/A', 'Condimentos', NULL, NULL, true),
  ('Chiles secos', 'Condimentos', NULL, NULL, true),
  ('Chile piquín', 'Condimentos', NULL, NULL, true),
  ('Consomé vegetal', 'Condimentos', NULL, NULL, true),
  ('Especias', 'Condimentos', NULL, NULL, true),
  ('Limón', 'Condimentos', NULL, NULL, true),
  ('Mostaza', 'Condimentos', NULL, NULL, true),
  ('Salsa de soya baja en sodio', 'Condimentos', NULL, NULL, true),
  ('Salsa inglesa', 'Condimentos', NULL, NULL, true),
  ('Salsa picante', 'Condimentos', NULL, NULL, true),
  ('Salsa tamari', 'Condimentos', NULL, NULL, true),
  ('Pimienta', 'Condimentos', NULL, NULL, true),
  ('Sazonadores S/ glutamato', 'Condimentos', NULL, NULL, true),
  ('Vainilla (esencia)', 'Condimentos', NULL, NULL, true),
  ('Vinagre', 'Condimentos', NULL, NULL, true),

  ('Agua de jamaica S/A', 'Bebidas', NULL, NULL, true),
  ('Agua de limón S/A', 'Bebidas', NULL, NULL, true),
  ('Agua mineral', 'Bebidas', NULL, NULL, true),
  ('Agua natural', 'Bebidas', NULL, NULL, true),
  ('Café S/A', 'Bebidas', NULL, NULL, true),
  ('Infusiones S/A', 'Bebidas', NULL, NULL, true),
  ('Té verde o negro S/A', 'Bebidas', NULL, NULL, true),

  ('Chicle S/A', 'Antojos', NULL, NULL, true),
  ('Gelatina light', 'Antojos', NULL, NULL, true),
  ('Merengues light', 'Antojos', NULL, NULL, true),
  ('Monk fruit', 'Antojos', NULL, NULL, true),
  ('Quinoa bites', 'Antojos', NULL, NULL, true),
  ('Splenda', 'Antojos', NULL, NULL, true),
  ('Stevia', 'Antojos', NULL, NULL, true)
)
INSERT INTO foodhelp.foods (name, food_group, base_quantity, unit, is_free_consumption, verified_at, created_at)
SELECT name, food_group, base_quantity, unit, is_free_consumption, now(), now()
FROM catalog;